LIBSRC = \
	pfile_createPSubFile.c \
	pfile_numOfArgs.c \
	pfile_pakClose.c \
	pfile_pakCloseSub.c \
	pfile_pakFind.c \
	pfile_pakOpen.c \
	pfile_pakOpenSub.c \
	pfile_pakRead.c \
	pfile_pakScanf.c \
	pfile_pakSeek.c \
	pfile_pakTell.c \
	pfile_va_listToArray.c
LIBOBJ=$(LIBSRC:.c=.o)
LIBOUT=libpfile.a

SRC=$(LIBSRC)
OBJ=$(LIBOBJ)
OUT=$(LIBOUT)

HEADERS=pfile.h

include ../makeinclude.macros

